// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ivweuuyavtpdgwrkxvsp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml2d2V1dXlhdnRwZGd3cmt4dnNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwNzY0NjMsImV4cCI6MjA2MjY1MjQ2M30.AZJ3wPKBgnzMRu0SS6Egiq6s_lN0ySB4CMC6uiUmuFc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);